global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "springmate-backend"
    scheme: https
    metrics_path: /actuator/prometheus

    tls_config:
      insecure_skip_verify: true

    basic_auth:
      username: prometheus@system.infra
      password: ae03a55f-7f71-46eb-afb7-91cdd8cf8ebd

    static_configs:
      - targets:
          - backend:8080
        labels:
          app: "springmate"
          env: "local"
          service: "backend"
